/**
 * Bootstrap Grid CKEditor plugin
 * Author: Cl!cker
 * Website: https://opencart.click
 *
 * Created specially for commercial OpenCart CKEditor Extension
 * Cannot be distributed or resold separately
 */

!function(){"use strict";CKEDITOR.plugins.add("cl_bs_grid",{lang:"en",requires:"widget,dialog",icons:"cl_bs_grid",init:function(i){var t=i.lang.cl_bs_grid,n="div",g="div",h="div";CKEDITOR.dialog.add("cl_bs_grid",this.path+"dialogs/cl_bs_grid.js"),i.addContentsCss(this.path+"css/editor.css"),i.ui.addButton("cl_bs_grid",{label:t.createBsGrid,command:"cl_bs_grid",icon:this.path+"icons/cl_bs_grid.png"}),i.widgets.add("cl_bs_grid",{allowedContent:"div(!ckebs-grid);div(!row,!row-*);div(!row,!row-*);div(!col-*-*);div(!col-*-*);",requiredContent:"div(ckebs-grid)",parts:{cl_bs_grid:"div.ckebs-grid"},editables:{content:""},template:'<div class="ckebs-grid"></div>',dialog:"cl_bs_grid",defaults:{},upcast:function(i){return"div"===i.name&&i.hasClass("ckebs-grid")},init:function(){for(var i=1,t=this.element.getChildCount();i<=t;i++)this.createEditable(12,i)},data:function(){if(this.data.colCount&&this.element.getChildCount()<1)for(var i=this.data.colCount,t=this.data.rowCount,s=this.data.breakpoint,r=this.parts.cl_bs_grid,l=1;l<=t;l++)this.createGrid(i,r,l,s,this.data)},str_replace:function(i,t,s){return s=(s=String(s).split(i)).join(t)},createGrid:function(i,t,s,r,l){let d='<div class="row row-'+s+(l.rowClass?" "+String(l.rowClass).trim():"")+'">';if(0===String(i).indexOf("col-")){var a=this.str_replace("col-","",i);i=(a=String(a).split("+")).length,"col"==r&&(r="col-");for(var c=0;c<i;c++){var e="<div> Col "+(c+1)+"</"+h+">";d=d+"<"+g+' class="'+r+a[c]+(l.colClass?" "+String(l.colClass).trim():"")+'">'+e+"</"+g+">"}}else for(c=1;c<=i;c++){var o="<div> Col "+c+"</"+h+">";d="col"==r?d+"<"+g+' class="col'+(l.colClass?" "+String(l.colClass).trim():"")+'">'+o+"</"+g+">":d+"<"+g+' class="'+r+Math.floor(12/i)+(l.colClass?" "+String(l.colClass).trim():"")+'">'+o+"</"+g+">"}d=d+"</"+n+">",t.appendHtml(d),this.createEditable(i,s)},createEditable:function(i,t){for(var s=1;s<=i;s++)this.initEditable("ckebs-grid"+t+s,{selector:".row-"+t+" > div:nth-child("+s+")"})}})}})}();